To drop (delete) all of the tables and views generated by the hiveddl.sql script, copy, paste, and excecute the following code in the Hive query editor in the HUE: 

DROP TABLE tweets_raw;
DROP TABLE tweets_raw;
DROP TABLE dictionary;
DROP TABLE time_zone_map;
DROP VIEW tweets_simple;
DROP VIEW tweets_clean;
DROP VIEW l1;
DROP VIEW l2;
DROP VIEW l3;
DROP VIEW tweets_sentiment;
DROP TABLE tweetsbi;

